#!/usr/bin/env python3
"""
build_encrypt.py

Encrypts content.html with a password using PBKDF2-SHA256 + AES-256-GCM,
matching what the browser's SubtleCrypto API does in app.js.

Usage:
    python3 build_encrypt.py "your-password-here"

Writes encrypted.js, which index.html loads. Re-run this any time you
change content.html or want to change the password.
"""
import base64
import json
import os
import sys

from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC
from cryptography.hazmat.primitives.ciphers.aead import AESGCM

ITERATIONS = 200_000


def encrypt(password: str, plaintext: bytes) -> dict:
    salt = os.urandom(16)
    iv = os.urandom(12)

    kdf = PBKDF2HMAC(
        algorithm=hashes.SHA256(),
        length=32,
        salt=salt,
        iterations=ITERATIONS,
    )
    key = kdf.derive(password.encode("utf-8"))

    aesgcm = AESGCM(key)
    ciphertext = aesgcm.encrypt(iv, plaintext, None)

    return {
        "salt": base64.b64encode(salt).decode(),
        "iv": base64.b64encode(iv).decode(),
        "ciphertext": base64.b64encode(ciphertext).decode(),
        "iterations": ITERATIONS,
    }


def main():
    if len(sys.argv) != 2:
        print('Usage: python3 build_encrypt.py "your-password"')
        sys.exit(1)

    password = sys.argv[1]

    with open("content.html", "rb") as f:
        plaintext = f.read()

    payload = encrypt(password, plaintext)

    with open("encrypted.js", "w") as f:
        f.write("// Auto-generated by build_encrypt.py — do not edit by hand.\n")
        f.write("const ENCRYPTED_PAYLOAD = ")
        json.dump(payload, f, indent=2)
        f.write(";\n")

    print("Wrote encrypted.js")
    print("Remember: the plaintext password lives only in your shell history / this command.")
    print("Don't commit content.html itself if you want the source hidden too — only encrypted.js is needed.")


if __name__ == "__main__":
    main()
